// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKL3aMJ68pkfP1dRk9yK-Cb4zpFzfagEE',
    appId: '1:695561249892:android:5d21ec8331e835a2f52b71',
    messagingSenderId: '695561249892',
    projectId: 'flutter-unaspfome-app',
    storageBucket: 'flutter-unaspfome-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrp7mLTzuWNLH5qpxuScdGLbtH4vHadyE',
    appId: '1:695561249892:ios:8b1aa8552246d73df52b71',
    messagingSenderId: '695561249892',
    projectId: 'flutter-unaspfome-app',
    storageBucket: 'flutter-unaspfome-app.appspot.com',
    androidClientId: '695561249892-0odfk84ug1vet4n9omapi9fro5dcdsrc.apps.googleusercontent.com',
    iosClientId: '695561249892-rd1sko1ual8o9d1itsdn4umn0eur4n0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.unaspFomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrp7mLTzuWNLH5qpxuScdGLbtH4vHadyE',
    appId: '1:695561249892:ios:f7fbf289712d90a7f52b71',
    messagingSenderId: '695561249892',
    projectId: 'flutter-unaspfome-app',
    storageBucket: 'flutter-unaspfome-app.appspot.com',
    androidClientId: '695561249892-0odfk84ug1vet4n9omapi9fro5dcdsrc.apps.googleusercontent.com',
    iosClientId: '695561249892-8q8v7eqf5a985qa8gl6rr0lej153eih6.apps.googleusercontent.com',
    iosBundleId: 'none',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl-Rf5nCI73OjAogBSfVVuUDoq8AfkM2M',
    appId: '1:695561249892:web:8e336eb76686b7ddf52b71',
    messagingSenderId: '695561249892',
    projectId: 'flutter-unaspfome-app',
    authDomain: 'flutter-unaspfome-app.firebaseapp.com',
    storageBucket: 'flutter-unaspfome-app.appspot.com',
    measurementId: 'G-H5J968NH75',
  );

}